version: '1.0'

services:
  postgresql:
    image: postgres:14
    container_name: docker_postgres14
    hostname: db
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data 
    environment:
      POSTGRES_PASSWORD: a


volumes:
  postgres:
